### ISSUE TITLE
document URL name duplication

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#12]
Hi,

Our publication's end up with URLs that repeat their titles in the URL.

This is because of the names we give to the publication folder and html file.

We should look at ways to remove this duplication, either programmatically or in a naming convention for the author to follow.

eg.

/dynamic_publishing_new_platforms_new_readers/dynamic_publishing_new_platforms_new_readers.html

Cheers

Simon

**Comment by dreh23** [comment]
Changing the logic programmatically:
1. Lokal serving:
We could use https://www.npmjs.com/package/connect-modrewrite to rewrite request to a subfolder, then we need to filter the index generation and get rid of the directory. This could be done in angularjs. aswell, but could have some sideeffects for assets that are loaded. 
2. Nginx proxy:
same as above but we will need to have some rewrite rule here as well.
I look into it.
3. Do nothing and wait for an API
Changing convention logic:
1. We could rename all files to index.html. This is lame I know.

**Comment by dreh23** [comment]
duplicate

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#12
