### ISSUE TITLE
jQuery Color isn’t pushed

### ISSUE THREAD

**Issue by furter** [consortium/hybrid-publishing-research#16]
I pushed a jQuery Color script on the research GitHub but now it is not automatically deployed on the site:
https://github.com/consortium/hybrid-publishing-research/blob/master/js/jquery.color-2.0b1.min.js

**Comment by dreh23** [comment]
I will redo the library pipeline and ensure everything is properly included (in the right loading order)

**Comment by dreh23** [comment]
Its now a bower dependency.

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#16
