### ISSUE TITLE
how do i install

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#17]
hi j

how do i install

>> Local Npm module "grunt-angular-htmlify" not found. Is it installed?

S

**Comment by dreh23** [comment]
This is wierd. grunt-angular-htmlify gets installed automatically when you run "grunt". It is referenced in the package.json file. Just retry - if you fail maybe you should wipe your local clone and retry. If you need more help we can meet.

**Comment by mrchristian** [comment]
Hi J,

I think I didn't wipe and reinstall a while back when you added or changed some components, I'll do a wipe and upgrade.

Ciao

S

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#17
