### ISSUE TITLE
site refreshing

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#18]
Hi J,

Should the research.consortium.io site be updating on its own. Ive added a new file and I'm not seeing it on the site.

S

**Comment by dreh23** [comment]
Compiling fails due to html errors. Site won't generate new index file. This is intended. We need to fix errors in documents. This should be done locally before you commit to github. If I run grunt index on the server:

    Validation started for.. dist/docs/book_liberation_manifesto/Book_Liberation_Manifesto.html
    1=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all a rticles." Line no: 91
    No of errors: 1
    Validation started for.. dist/docs/documentation/documentation.html
    1=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 230
    2=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 232
    3=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 233
    4=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 234
    5=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 235
    6=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 237
    7=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 238
    8=> "Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections." Line no: 369
    9=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles." Line no: 65
    No of errors: 9
    Validation started for.. dist/docs/empowering_publishers_to_innovate/Empowering_Publishers_to_Innovate.html
    >> Validation successful..
    Validation started for.. dist/docs/hpc_research_plan_2014-15/hpc_research_plan_2013-15.html
    >> Validation successful..
    Validation started for.. dist/docs/traces_on_the_archive/traces_on_the_archive.html
    1=> "Element title must not be empty." Line no: 23
    2=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    3=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    4=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    5=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    6=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    7=> "Bad character < after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    8=> "Bad character   after <. Probable cause: Unescaped <. Try escaping it as &lt;." Line no: 26
    9=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 73
    10=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 77
    11=> "End tag i violates nesting rules." Line no: 78
    12=> "No u element in scope but a u end tag seen." Line no: 78
    13=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 85
    14=> "No p element in scope but a p end tag seen." Line no: 86
    15=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 89
    16=> "End tag i violates nesting rules." Line no: 90
    17=> "No u element in scope but a u end tag seen." Line no: 90
    18=> "End tag i violates nesting rules." Line no: 96
    19=> "No u element in scope but a u end tag seen." Line no: 96
    20=> "No p element in scope but a p end tag seen." Line no: 112
    21=> "No p element in scope but a p end tag seen." Line no: 170
    22=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 175
    23=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 176
    24=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 176
    25=> "End tag i violates nesting rules." Line no: 176
    26=> "No u element in scope but a u end tag seen." Line no: 176
    27=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 177
    28=> "& did not start a character reference. (& probably should have been escaped as &amp;.)" Line no: 177
    29=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 182
    30=> "End tag i violates nesting rules." Line no: 183
    31=> "No u element in scope but a u end tag seen." Line no: 183
    32=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 188
    33=> "No p element in scope but a p end tag seen." Line no: 189
    34=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 195
    35=> "No p element in scope but a p end tag seen." Line no: 196
    36=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 205
    37=> "No p element in scope but a p end tag seen." Line no: 206
    38=> "An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images." Line no: 212
    39=> "No p element in scope but a p end tag seen." Line no: 213
    40=> "Duplicate ID 3." Line no: 237
    41=> "The first occurrence of ID 3 was here." Line no: 227
    42=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles." Line no: 63
    No of errors: 42
    Validation report generated: validation-report.json
    Warning: 52 total unignored HTML validation errors. Use --force to continue.

    Aborted due to warnings.

**Comment by dreh23** [comment]
Got error count down. We need to solve the header tag issue.

    slim grunt index
    Running "validation:files" (validation) task
    Validation started for.. dist/docs/book_liberation_manifesto/Book_Liberation_Manifesto.html
    1=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles." Line no: 91
    No of errors: 1
    Validation started for.. dist/docs/documentation/documentation.html
    1=> "Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections." Line no: 370
    2=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles." Line no: 66
    3=> "Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools)." Line no: 52
    No of errors: 3
    Validation started for.. dist/docs/empowering_publishers_to_innovate/Empowering_Publishers_to_Innovate.html
    >> Validation successful..
    Validation started for.. dist/docs/hpc_research_plan_2014-15/hpc_research_plan_2013-15.html
    >> Validation successful..
    Validation started for.. dist/docs/traces_on_the_archive/traces_on_the_archive.html
    1=> "Article lacks heading. Consider using h2-h6 elements to add identifying headings to all articles." Line no: 62
    No of errors: 1
    Validation report generated: validation-report.json
    Warning: 5 total unignored HTML validation errors. Use --force to continue.

    Aborted due to warnings.

**Comment by mrchristian** [comment]
AOK

**Comment by dreh23** [comment]
I could override the h2-h6 error. But we should refine the template/documentation.

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#18
