### ISSUE TITLE
summary needs to use DC.contributor, up to 4 times

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#19]
Hi

The document summary on the index page needs to use up to 4x DC.contributor

<META NAME="DC.contributor" CONTENT="Simon Worthington">
<META NAME="DC.contributor" CONTENT="Christina Kral">

Thanks

S

**Comment by dreh23** [comment]
I added 4 contributors  to a test document, there are displayed in the index. The css isn't to well it cuts off some of the names.

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#19
