### ISSUE TITLE
ordered list numbering HTML

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#20]
Hi

I want default numbers to appear on the OL, LI tag, see line 83

https://github.com/consortium/hybrid-publishing-research/blob/master/dist/docs/traces_on_the_archive/traces_on_the_archive.html#L83

Has this been turned off in the CSS?

Thanks

S

**Comment by mrchristian** [comment]
Hi,

The question also applies to UL as well, as here on line 123 where I'm trying to apply a disk to list items, although I'm happy to not have a marking, its just a question about how are lists being styled.

https://github.com/consortium/hybrid-publishing-research/blob/master/dist/docs/traces_on_the_archive/traces_on_the_archive.html#L123

Thanks

S

**Comment by furter** [comment]
Fixed: I added it in the overriding css:
ul > bullets
ol > decimal
Normally I should have been the default, but I guess it was turned off in the bootstrap.

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#20
