### ISSUE TITLE
Second para style option not to indent

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#21]
Hi,

Can we get an optional style not to indent paragraphs?

I need on things like this line two.

https://github.com/consortium/hybrid-publishing-research/blob/master/dist/docs/traces_on_the_archive/traces_on_the_archive.html#L72

Cheers

S

**Comment by furter** [comment]
Fixed: added class "no-indent"

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#21
