### ISSUE TITLE
Add Google Analytics to repository and publications

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#27]
Hi J,

Can you add Google analytics to the Git repro, overall, to the Research Viewer index and to publications.

Thanks

S

**Comment by mrchristian** [comment]
HI J

Here is the ID

UA-47101218-3

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47101218-3', 'auto');
  ga('send', 'pageview');

</script>

S

**Comment by codingisacopingstrategy** [comment]
Google Analytics is *evil*

http://piwik.org/

**Comment by codingisacopingstrategy** [comment]
Because so many sites use Google Analytics Google can track our web surfing habits into the smallest details.

**Comment by codingisacopingstrategy** [comment]
Locally hosted analytics are the more ethical alternative, because even if you are spying on your visitors, at least you are only spying on them while they are on your site, and you are not adding to a larger surveillance network (GA).

**Comment by mrchristian** [comment]
Hi,

We are having some local analytics setup on new servers piwik. I think Google is getting tracking data on your sites whether you add a tracking code or not. Since NSA is copying all data all the time were all fckd.

But yes better to move any historical data out of Googl´s hand and US companies open to subpoena. Hence our move the DE machines, off cloud.

Once Piwiki is up we'll switch codes.

Obviously we all know it goes on, but here is an Intercept article from yesterday on Jacob Appelbaum

https://firstlook.org/theintercept/2015/06/20/wikileaks-jacob-appelbaum-google-investigation/

QUOTE

Newly unsealed court documents obtained by The Intercept reveal the Justice Department won an order forcing Google to turn over more than one year’s worth of data from the Gmail account of Jacob Appelbaum (pictured above), a developer for the Tor online anonymity project who has worked with WikiLeaks as a volunteer. The order also gagged Google, preventing it from notifying Appelbaum that his records had been provided to the government.

END QUOTE

S

**Comment by dreh23** [comment]
You load sixteen tons, what do you get
Another day older and deeper in debt
Saint Peter don't you call me 'cause I can't go
I owe my soul to the company store

Google it is. Lets make a quick transition to a more happier life!

**Comment by dreh23** [comment]
#54

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#27
