### ISSUE TITLE
index page commit link

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#35]
Hi

I changed the index page commit link to the commits page, for the most current updates.

Before hand the link just went to the updates for the index doc and this isn't very revealing, this list of commits is more useful and the user can still review the latest change in the doc

The link now goes here

https://github.com/consortium/hybrid-publishing-research/commits/

Cheers

S

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#35
