### ISSUE TITLE
Footnote link from footnote number to footnote

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#47]
hi

footnote numbers not linking to footnotes from text, the ids and anchor links are present but not working in browser.

https://research.consortium.io/docs/book_liberation_manifesto/Book_Liberation_Manifesto.html#fn19

These links work from footnotes to footnote number.

Thanks

Simon

**Comment by furter** [comment]
Fixed!

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#47
