### ISSUE TITLE
H3 irregular indenting chrome osx

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#48]
hi

in the following chapter the H3 headers below the header Majors Stages have an irregular left indent

https://research.consortium.io/docs/book_liberation_manifesto/Book_Liberation_Manifesto.html#infrastructure

Ive checked the HTML and that looks good.

Simon

**Comment by mrchristian** [comment]
Hi,

Similar issues of H3 in the chp. 'The Plan', after rapid prototyping

S

**Comment by mrchristian** [comment]
Hi 

The H3 issue is also happening on Traces on the archive

https://research.consortium.io/docs/traces_on_the_archive/traces_on_the_archive.html

S

**Comment by furter** [comment]
Fixed

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#48
