### ISSUE TITLE
index fixes

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#50]
Hi

Can we get the publication type on the index page publication information list.

Also the [[]] needs fixing around the name.

For the moment I´ll cram all names into one field and keep it short, as I suspect we cant pick up multiple names or cut off line display if it goes over a character count to tidy things up.

Thanks

S

**Comment by furter** [comment]
This should be assigned to Johannes, I don’t know what’s wrong there and how to remove the [[]] …

**Comment by mrchristian** [comment]
Hi J,

Bit of a just in time day :-)

S

On 22/06/2015 16:21, Johannes Amorosa wrote:
> Closed #50
> <https://github.com/consortium/hybrid-publishing-research/issues/50>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/consortium/hybrid-publishing-research/issues/50#event-336756801>.
>

-- 
we gladly feast on those who would subdue us - http://metamute.org

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#50
