### ISSUE TITLE
New publication not showing in index on web site

### ISSUE THREAD

**Issue by mrchristian** [consortium/hybrid-publishing-research#57]
Hi J,

I added a new publication 'digital_writers_style_guide' and its not showing up in the website index page.

The same thing was happening when I worked on the file locally, I could view the publication html file in a browser, but could not see it listed in the local index.

The file has been validated.

I thought then I'd try it online, as maybe my local grunt meta parser might not be working.

But alas no.

So looks like an index issues.

Cheers

S

**Comment by dreh23** [comment]
Hmm, I did introduce a index creation regression. I,ll debug.

**Comment by dreh23** [comment]
No. it was a caching error. Seems to be solved now.

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#57
